#include "main.h"




void HAL_MspInit(void)
{
	// SET PRIORITIES
	HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);

	//ENABLE SYSTEM EXCEPTIONS
	SCB->SHCSR |= 0x7 <<16;  //USAGE FAULT, MEM FAULT AND BUS FAULT EXCEPTIONS

	//CONFIG PRIO FOR SYSTEM EXCEPTION
	HAL_NVIC_SetPriority(MemoryManagement_IRQn,0,0);
	HAL_NVIC_SetPriority(BusFault_IRQn,0,0);
	HAL_NVIC_SetPriority(UsageFault_IRQn,0,0);

}

void HAL_UART_MspInit(UART_HandleTypeDef *huart)
{
	GPIO_InitTypeDef GPIO_UART;

	//ENABLE CLOCK FOR USART2 AND RELATED GPIO
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_USART2_CLK_ENABLE();
	//DO PIN MUXING CONFIG
	GPIO_UART.Pin = GPIO_PIN_2;
	GPIO_UART.Mode = GPIO_MODE_AF_PP;
	GPIO_UART.Pull = GPIO_PULLUP;
	GPIO_UART.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_UART.Alternate = GPIO_AF7_USART2; //TX
    HAL_GPIO_Init(GPIOA, &GPIO_UART);
    GPIO_UART.Pin = GPIO_PIN_3;
    HAL_GPIO_Init(GPIOA, &GPIO_UART); //RX

    //ENABLE IRQ, AND PRIO SETTINGS
    HAL_NVIC_EnableIRQ(USART2_IRQn);
    HAL_NVIC_SetPriority(USART2_IRQn,15,0);

}
